export const cards = [
  {
    id: 1,
    title: "Java",
    desc: "Study Java",
    img: "./img/java1.png",
  },
  {
    id: 2,
    title: "C++",
    desc: "Study C++",
    img: "./img/java.jpg",
  },
  {
    id: 3,
    title: "React",
    desc: "Cover all React in One Go",
    img: "./img/react.jpg",
  },
  {
    id: 4,
    title: "Node",
    desc: "Complete Node",
    img: "./img/node.png",
  },
  {
    id: 5,
    title: "Web Development",
    desc: "Complete HTML CSE JS",
    img: "./img/html.png",
  },
  {
    id: 6,
    title: "Cloud Computing",
    desc: "What is Cloud Computing",
    img: "./img/cloud.jpeg",
  },
  {
    id: 7,
    title: "Autometa",
    desc: "What is Autometa?🤔",
    img: "https://images.pexels.com/photos/4820241/pexels-photo-4820241.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 8,
    title: "Study Rooms",
    desc: "Coming Soon",
    img: "./img/study.jpg",
  },
];

export const projects = [
  {
    id: 1,
    img: "./img/java1.png",
    pp: "./img/Formal.jpg",
    cat: "Java Metro Map",
    username: "Siddhant Lamba",
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/270408/pexels-photo-270408.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Logo Design",
    username: "Rohan Chainani",
  },
  {
    id: 3,
    img: "./img/reactp.jpg",
    pp: "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "React Projects",
    username: "Ayush Tiwari",
  },
  {
    id: 4,
    img: "https://images.pexels.com/photos/4348404/pexels-photo-4348404.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "./img/sid.jpeg",
    cat: "Python Voice Assistant",
    username: "Jitin Kumar",
  },
  {
    id: 5,
    img: "https://images.pexels.com/photos/4458554/pexels-photo-4458554.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "./img/viky.jpeg",
    cat: "Data Science",
    username: "Vikrant",
  },
  {
    id: 6,
    img: "./img/java.jpg",
    pp: "./img/Formal.jpg",
    cat: "Data Structures",
    username: "Siddhant Lamba",
  },
  {
    id: 7,
    img: "./img/node.png",
    pp: "./img/viky.jpeg",
    cat: "Node",
    username: "Vikrant",
  },
  {
    id: 8,
    img: "https://images.pexels.com/photos/4065876/pexels-photo-4065876.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "./img/sid.jpeg",
    cat: "Node js",
    username: "Jitin Kumar",
  },
];

export const gigs = [
  {
    id: 1,
    img: "./img/java1.png",
    pp: "./img/Formal.jpg",
    desc: "I will make you learn Core Java with Complete Basics",
    price: 499,
    star: 5,
    username: "Siddhant Lamba",
  },
  {
    id: 2,
    img: "./img/javap.jpg",
    pp: "./img/Formal.jpg",
    desc: "I can make you learn Data Structures And Algorithms easy and in efficiat way",
    price: 999,
    star: 5,
    username: "Siddhant Lamba",
  },
  {
    id: 3,
    img: "./img/java.jpg",
    pp: "./img/Formal.jpg",
    desc: "Insights of production and deployment",
    price: 499,
    star: 5,
    username: "Siddhant Lamba",
  },
  {
    id: 4,
    img: "./img/python.png",
    pp: "./img/sid.jpeg",
    desc: "Learn Python from basics to boom",
    price: 499,
    star: 4,
    username: "Jitin Kumar",
  },
  {
    id: 5,
    img: "./img/cload.png",
    pp: "./img/Formal.jpg",
    desc: "Cloud Computing Fundamentals",
    price: 299,
    star: 5,
    username: "Siddhant Lamba",
  },
  {
    id: 6,
    img: "./img/react.jpg",
    pp: "./img/viky.jpeg",
    desc: "I will Make you learn React",
    price: 499,
    star: 4,
    username: "Vikrant",
  },
  {
    id: 7,
    img: "./img/reactp.jpg",
    pp: "./img/viky.jpeg",
    desc: "I will teach desiging and photo editing",
    price: 999,
    star: 5,
    username: "Vikrant",
  },
  {
    id: 8,
    img: "./img/node.png",
    pp: "./img/sid.jpeg",
    desc: "I will Teach you  Nodejs",
    price: 999,
    star: 4,
    username: "Sidhant Lamba",
  },
];

export const moreinfo =[
{id: 1,
  h1:"I will make you teach Java",
  img1: "./img/java1.png",
  img2: "./img/java.jpg",
  img3: "./img/javap.jpg",

  pp: "./img/Formal.jpg",
  desc: "I use an AI program to create images based on text prompts. This means I can help you to create a vision you have through a textual description of your scene without requiring any reference images. Some things I've found it often excels at are: Character portraits (E.g. a picture to go with your DnD character) Landscapes (E.g. wallpapers, illustrations to compliment a story) Logos (E.g. Esports team, business, profile picture) You can be as vague or as descriptive as you want. Being more vague will allow the AI to be more creative which can sometimes result in some amazing images. You can also be incredibly precise if you have a clear image of what you want in mind. All of the images I create are original and will be found nowhere else. If you have any questions you're more than welcome to send me a message.",
  price: 999,
  desc2:"Hii my name is Siddhant Lamba I am Good at java and can make you learn too",
  star: 5,
  username: "Siddhant Lamba",},
  {id: 2,
    h1:"I will make you",
    img1: "./img/java1.png",
    img2: "./img/java.jpg",
    img3: "./img/javap.jpg",
  
    pp: "./img/Formal.jpg",
    desc: "I use an AI program to create images based on text prompts. This means I can help you to create a vision you have through a textual description of your scene without requiring any reference images. Some things I've found it often excels at are: Character portraits (E.g. a picture to go with your DnD character) Landscapes (E.g. wallpapers, illustrations to compliment a story) Logos (E.g. Esports team, business, profile picture) You can be as vague or as descriptive as you want. Being more vague will allow the AI to be more creative which can sometimes result in some amazing images. You can also be incredibly precise if you have a clear image of what you want in mind. All of the images I create are original and will be found nowhere else. If you have any questions you're more than welcome to send me a message.",
    price: 999,
    desc2:"Hii my name is Siddhant Lamba I am Good at java and can make you learn too",
    star: 5,
    username: "Siddhant Lamba",},
    {id: 3,
      h1:"I will make you teach Python",
      img1: "./img/java1.png",
      img2: "./img/java.jpg",
      img3: "./img/javap.jpg",
    
      pp: "./img/Formal.jpg",
      desc: "I use an AI program to create images based on text prompts. This means I can help you to create a vision you have through a textual description of your scene without requiring any reference images. Some things I've found it often excels at are: Character portraits (E.g. a picture to go with your DnD character) Landscapes (E.g. wallpapers, illustrations to compliment a story) Logos (E.g. Esports team, business, profile picture) You can be as vague or as descriptive as you want. Being more vague will allow the AI to be more creative which can sometimes result in some amazing images. You can also be incredibly precise if you have a clear image of what you want in mind. All of the images I create are original and will be found nowhere else. If you have any questions you're more than welcome to send me a message.",
      price: 999,
      desc2:"Hii my name is Siddhant Lamba I am Good at java and can make you learn too",
      star: 5,
      username: "Siddhant Lamba",}
]

